### ISSUE TITLE
4k Resolution not supported

### ISSUE THREAD

**Issue by bozio** [JocysCom/TextToSpeech#39] opened 2020-03-12 06:22 UTC
Monitor Display doen't work at the resolution 3840 x 2160

**Comment by ryankhart** [comment] 2020-07-07 13:56
I can confirm. This works on my 1440p monitor, but not my 4K TV. I'm happy to provide any diagnostic info if need be, but I'd need some instruction on how to do that.

**Comment by wobbo** [comment] 2020-08-05 18:56
I have the same problem. It works in 2560x1440.

**Comment by EJocys** [comment] 2020-08-05 19:28
I am wondering if 4K resolution is using Chroma Subsampling other than 4:4:4, which means that actual colours of some pixels are going to differ. We tested this plugin on RGB 8-bit panels with Chroma Subsampling 4:4:4 mode. How many bits (8, 10 or 12) are you using and can you find out Chroma Subsampling (4:4:4, 4:2:2 or 4:2:0) used in 4K mode (must be somewhere in video card settings)?

More about Chroma Subsampling 4:4:4 vs 4:2:2 vs 4:2:0:
https://youtu.be/yinOtVTWJFY

**Comment by ryankhart** [comment] 2020-08-07 03:21
I'm currently on a break from WoW right now for reasons unrelated to this issue, but I may test out this idea if I end up jumping into Shadowlands. (although Baldur's Gate 3 and Cyberpunk 2077 may keep me away from WoW for some time lol)

**Comment by wobbo** [comment] 2020-08-09 13:00
My [DUAL-GTX1060-3G](https://www.asus.com/us/supportonly/DUAL-GTX1060-3G/HelpDesk_Manual/) offers 32-bit 8bpc 4:4:4, 4:2:2 and RGB.

**Comment by EJocys** [comment] 2020-08-09 13:54
@wobbo:

Could you do a test inside the Monitor app:

1. Open [Options] tab, open [Monitor: Display] tab
2. Click [Create Image] button
3. Click [Capture Image] button.
4. If it works then "Results" text box will show: &lt;message... If it fails then it should display the reason in "Status" text box.

![image](https://user-images.githubusercontent.com/11958537/89733628-9e845b80-da4e-11ea-85df-8be0bf4ee7eb.png)

Please check if you have these settings:

1. Set GPU settings to: 8ppc, 4:4:4, RGB
2. In WoW Graphics options, set resolution scaling at 4K to: 100%
3. To make sure that colour line is not covered, In WoW addon settings, set LEFT and TOP position of colour pixel line to: 10

**Comment by wobbo** [comment] 2020-08-11 21:36
Today I have a new set of gear. New monitor 3840x2160. Now offers Highest 32-bit, DisplayPort 1.4, 1.4 cable, 4k, 10bpc, YCbCr 444, 60Hz, HDR. This set did not solve the problem. I'm not going to carry out your assignment until Friday. Thank you for all your time. 


_[iiyama ProLite XB3288UHSU-B1](https://iiyama.com/gl_en/products/prolite-xb3288uhsu-b1/)_

**Comment by wobbo** [comment] 2020-08-12 11:53
I tried it. But it didn't. I tried to change the I position. It's weird that the y is set to 200px but shows different. 
![image](https://user-images.githubusercontent.com/12646389/90012145-24004980-dca3-11ea-92da-4e6cd654bfca.png)

**Comment by wobbo** [comment] 2020-09-21 17:45
After a lot of testing I found out that it works until the reach of 3840*1919. If I set 3840*1920 It doesn't work anymore. I also tried the opposite, counting down from step four step 3840*2160 to 1000*2160. But that didn't matter. So it seems the X is not the problem.  

![Capture 001](https://user-images.githubusercontent.com/12646389/93801818-e5b35e00-fc42-11ea-8b05-f1c2f4ca3cf5.PNG)

**Comment by EJocys** [comment] 2020-09-21 21:32
Thank you for testing. I hope to debug this app on 4K monitor on Friday and see if I can fix this issue.

**Comment by wobbo** [comment] 2020-09-22 14:35
If you need more info or test, let me know.

**Comment by EJocys** [comment] 2020-09-24 20:35
@wobbo 

I've made some fixes on the Monitor application. For example: application was failing to capture image from screen at correct location if windows reported more than one screen (PC monitor). Now application looks for all screens and correct coordinates.

I've uploaded updated version here for you to test:
https://www.jocys.com/files/other/JocysCom.TextToSpeech.Monitor_3.2.10.zip

I've added extra buttons on "Debug and Test" tab which will help to investigate further if updated version won't fix the problem.

![image](https://user-images.githubusercontent.com/11958537/94196893-e94a1d80-feac-11ea-94be-68a5ec7b60d6.png)

**Comment by wobbo** [comment] 2020-10-09 13:35
I am sorry, but where is the button "Debug and Test"?

**Comment by EJocys** [comment] 2020-10-09 16:56
@wobbo: My mistake, I've meant "Debug and Tests" group box. I've added "Screen:" drop-down list and [Capture Screen & Save] button which captures selected "Screen:" to image file and opens folder in windows explorer. This allows to see what image application tries to analyse wen searching for colour pixels (encoded text message).

**Comment by wobbo** [comment] 2020-10-13 17:49
I' m going to check this officer the new big update 14 October. Let's find out if the problem is solved or worse... ;-p

**Comment by wobbo** [comment] 2020-10-16 20:26
Very bad news. You probably experience it yourself. A lot aren't working anymore or not even visible. 
At least the chat is still working. 

Let's leave the 4k issue for a while and focus on the new program.

**Comment by wobbo** [comment] 2020-10-24 19:51
VJocys solved #43, #44 and #45! Now I'm back with this one #39. Sorry I'm coming with so many issues. I even made a new one #46. 

What can I do to help resolve this issue?

**Comment by VJocys** [comment] 2020-10-25 01:02
Coloured pixel line In 3840x2160 Wow and TTS Monitor screenshot (TOP line in image below) is **distorted**.

Coloured pixel line must be **single** and **clean** (like BOTTOM one in image below).
Correct start of the line two examples (WoW game uses second one example - each second pixel is black #000000):
```
#220000,#002200,#000022...
#220000,#000000,#002200,#000000,#000022,#000000...
```
![Pixels](https://user-images.githubusercontent.com/11961339/97096528-b048c880-1665-11eb-9245-0125ff1cc2f6.png)

Because (if) pixel line is distorted, TTS Monitor can't find it and read it. Maybe there is something set in Video Card or Windows options... that leads to image distortion, resizing.

**Comment by wobbo** [comment] 2020-10-25 12:19
I don't think Nvidia is the causing of this problem. I need to find out if there isn't option to make the UI keep 1:1xp or something. Maybe in the config.wtf?

![line](https://user-images.githubusercontent.com/12646389/97106688-760e1400-16c3-11eb-9664-acda6c760e9e.png)

**Comment by wobbo** [comment] 2020-10-25 12:39
![full windows](https://user-images.githubusercontent.com/12646389/97107254-e23e4700-16c6-11eb-9409-7fea91cae31e.png)

It keeps working fine until WoW reaches 3840×1919.

**Comment by EJocys** [comment] 2020-10-25 13:32
@wobbo:

Great findings. It looks like addon have to un-scale frame (if possible) with pixels to a size which will produce pixel perfect image.

**Comment by EJocys** [comment] 2020-10-25 13:45
@wobbo 
I will try to prevent scaling on TTS monitor test form.

**Comment by wobbo** [comment] 2020-10-25 13:51
At the same time I want to create a new topic in the WoW forum. Only I have no idea how I can explain this...

**Comment by VJocys** [comment] 2020-10-25 14:07
Coloured pixel line is distorted not only in WoW game, but in TTS Monitor too in PNG 3840x2160 screenshot (if screenshot itself is not distorted):

![Pixels_TTS_Monitor](https://user-images.githubusercontent.com/11961339/97109057-131f7b80-16c9-11eb-912f-53b46f6b6a4d.png)

That means, that problem reaches beyond WoW game, and affects Windows programs too... at least, when WoW game is running.

**Comment by wobbo** [comment] 2020-10-25 14:17
Do you mean it's not possible to solve this?

**Comment by VJocys** [comment] 2020-10-25 14:27
My monitor is 2560x1440. I can theorise only, why 4K doesn't work.
Both... Fullscreen and Windowed mode (in WoW game Display settings) doesn't work?

**Comment by EJocys** [comment] 2020-10-25 14:49
I've tested TTS monitor on 4K. Made version TTS Monitor v3.3.6 DPI aware. Image test works now on scaled layout in Windows. VJocys will upload new version soon.

**Comment by wobbo** [comment] 2020-10-25 15:42
Until then the maximum 16:9 aspect ratio is **3412** × 1919.

**Comment by VJocys** [comment] 2020-10-25 15:59
New versions of TTS Monitor 3.3.6 uploaded.

**Comment by wobbo** [comment] 2020-10-25 16:27
I didn't got it working yet. Here it's looking like nothing changed.

**Comment by wobbo** [comment] 2020-10-25 16:47
![new](https://user-images.githubusercontent.com/12646389/97113353-15460200-16ea-11eb-8d7b-d9c00c2c35e4.png)

**Comment by wobbo** [comment] 2020-10-25 16:51
![new no button](https://user-images.githubusercontent.com/12646389/97113418-77066c00-16ea-11eb-87e5-9cbbc7363332.png)

It seems the button is away.

**Comment by VJocys** [comment] 2020-10-25 17:12
You need to enable "Dialogues, books, mail, etc." checkbox in WoW Addon for "Stop" and "Play" buttons to be visible in WoW's Log frame.

![WoW_Addon_Quests_Enabled](https://user-images.githubusercontent.com/11961339/97113705-0d835f00-16e4-11eb-8709-d4f1f96dc9d3.png)

WoW Addon may not work still (because of distorted pixel line). But new version of TTS Monitor 3.3.6 (2020-10-25) may be able to read its own coloured pixel line on 4K monitor now... you can test that...

TTS Monitor > [Options] tab > [Monitor: Display] tab > click on [Create Image] button.

**Comment by wobbo** [comment] 2020-10-25 17:29
By the way, thanks for helping me!

**Comment by EJocys** [comment] 2020-10-25 18:15
I was able to replicate the problem on 4K monitor with WoW addon. Now it is just a case of finding finding how it could be resolved in the LUA code :).

**Comment by VJocys** [comment] 2020-10-25 18:52
Updated WoW Addon to version 9.0.1.5 (2020-10-25)

XML: Fix for 4K monitors - coloured pixel line's "FontHeight" value fixed from "1" pt to "0.75" pt (1px).

**Comment by wobbo** [comment] 2020-10-25 20:57
YES, It works!

**Comment by EJocys** [comment] 2020-10-25 21:09
@wobbo 
Thank you for your help.

Kind regards,
Evaldas Jocys

**Comment by wobbo** [comment] 2020-10-25 21:10
It stil  seems the button is away.

**Closed by EJocys** 2020-10-25 21:09 UTC

**Comment by wobbo** [comment] 2020-10-25 21:11
I using a test version, I don't know which one that is part this. This one works.

**Comment by wobbo** [comment] 2020-10-25 21:13
The title says 3.2.10 (2020-10-11) but I remembered that wasn't ok.

**Comment by wobbo** [comment] 2020-10-25 21:17
This one:
[JocysCom.TextToSpeech.Monitor.exe.zip](https://github.com/JocysCom/TextToSpeech/files/5435986/JocysCom.TextToSpeech.Monitor.exe.zip)

**Comment by VJocys** [comment] 2020-10-25 23:46
TTS Monitor and WoW Addon latest versions are always under [ Download ] link:

https://www.jocys.com/TTS
https://github.com/JocysCom/TextToSpeech

https://www.jocys.com/Files/Software/JocysCom-TextToSpeech-WoW.zip
